table 55205 "Registro PDF Costos"
{
    Caption = 'Registro PDF Costos';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Posting Date"; Date)
        {
            Caption = 'Fecha registro';
            DataClassification = CustomerContent;
        }
        field(2; "File Name"; Text[250])
        {
            Caption = 'Nombre archivo';
            DataClassification = CustomerContent;
        }
        field(3; "PDF Content"; Blob)
        {
            Caption = 'Contenido PDF';
            DataClassification = CustomerContent;
        }
        field(4; "Generated At"; DateTime)
        {
            Caption = 'Generado el';
            DataClassification = CustomerContent;
        }
        field(5; "Generated By"; Code[50])
        {
            Caption = 'Generado por';
            DataClassification = EndUserIdentifiableInformation;
        }
    }

    keys
    {
        key(PK; "Posting Date")
        {
            Clustered = true;
        }
    }

    procedure SetPDF(PdfInStream: InStream)
    var
        PdfOutStream: OutStream;
    begin
        Clear("PDF Content");
        "PDF Content".CreateOutStream(PdfOutStream);
        CopyStream(PdfOutStream, PdfInStream);
    end;

    procedure GetPDF(var PdfInStream: InStream): Boolean
    begin
        CalcFields("PDF Content");

        if not "PDF Content".HasValue then
            exit(false);

        "PDF Content".CreateInStream(PdfInStream);
        exit(true);
    end;
}