codeunit 130401 "CAL Test Management"
{
    SingleInstance = true;

    trigger OnRun()
    begin
    end;

    var
        Window: Dialog;
        Mode: Option Test,Publish;
        AddingTestCodeunitsMsg: Label 'Adding Test Codeunits @1@@@@@@@', Locked = true;
        SelectTestsToRunQst: Label 'Active &Line,Active &Codeunit,&All', Locked = true;
        SelectTestsToImportQst: Label '&Select Test Codeunits,&All Test Codeunits', Locked = true;
        SelectTestsToImportFromTCMQst: Label '&Select Test Codeunits,&All Test Codeunits,&Get Tests Codeunits based on Modified Objects,Get Tests Codeunits based on Selected &Objects', Locked = true;
        SelectCodeunitsToRunQst: Label ',Active &Codeunit,&All', Locked = true;
        DefaultTxt: Label 'DEFAULT', Locked = true;
        DefaultSuiteTxt: Label 'Default Suite - Autogenerated', Locked = true;
        ObjectNotCompiledErr: Label 'Object not compiled.', Locked = true;
        WindowUpdateDateTime: DateTime;
        NoOfRecords: Integer;
        i: Integer;
        AddingTestsBasedOnChurnMsg: Label 'Adding %1 test codeunits based on churn @1@@@@@@@', Locked = true;
        NoModifiedObjectsFoundMsg: Label 'No modified objects found.', Locked = true;

    [Scope('Personalization')]
    procedure SETPUBLISHMODE()
    begin
        Mode := Mode::Publish;
    end;

    [Scope('Personalization')]
    procedure SETTESTMODE()
    begin
        Mode := Mode::Test;
    end;

    [Scope('Personalization')]
    procedure ISPUBLISHMODE(): Boolean
    begin
        EXIT(Mode = Mode::Publish);
    end;

    [Scope('Personalization')]
    procedure ISTESTMODE(): Boolean
    begin
        EXIT(Mode = Mode::Test);
    end;

    [Scope('Personalization')]
    procedure DoesTestCodeunitExist(ID: Integer): Boolean
    var
        AllObjWithCaption: Record 2000000058;
    begin
        AllObjWithCaption.RESET;
        AllObjWithCaption.SETRANGE("Object ID", ID);
        AllObjWithCaption.SETRANGE("Object Type", AllObjWithCaption."Object Type"::Codeunit);
        AllObjWithCaption.SETRANGE("Object Subtype", 'Test');
        EXIT(NOT AllObjWithCaption.ISEMPTY);
    end;

    procedure GetTestCodeunitsSelection(CALTestSuite Record: 130400")
    var
        CALTestLine: Record 130401;
        AllObjWithCaption: Record 2000000058;
        TempAllObjWithCaption Record: 2000000058" temporary;
        CALTestCoverageMap: Record 130406;
        CALTestGetCodeunits: Page130403;
        Selection: Integer;
    begin
        IF CALTestCoverageMap.ISEMPTY THEN
            Selection := STRMENU(SelectTestsToImportQst, 1)
        ELSE
            Selection := STRMENU(SelectTestsToImportFromTCMQst, 1);

        IF Selection = 0 THEN
            EXIT;

        CASE Selection OF
            1:
                BEGIN
                    CALTestGetCodeunits.LOOKUPMODE := TRUE;
                    IF CALTestGetCodeunits.RUNMODAL = ACTION::LookupOK THEN BEGIN
                        CALTestGetCodeunits.SETSELECTIONFILTER(AllObjWithCaption);
                        AddTestCodeunits(CALTestSuite, AllObjWithCaption);
                    END;
                END;
            2:
                BEGIN
                    CALTestLine.SETRANGE("Test Suite", CALTestSuite.Name);
                    CALTestLine.DELETEALL(TRUE);
                    IF GetTestCodeunits(TempAllObjWithCaption) THEN
                        RefreshSuite(CALTestSuite, TempAllObjWithCaption);
                END;
            3:
                GetTestCodeunitsForModifiedObjects(CALTestSuite.Name);
            4:
                GetTestCodeunitsForSelectedObjects(CALTestSuite.Name);
        END;
    end;

    local procedure GetTestCodeunits(var ToAllObjWithCaption Record: 2000000058"): Boolean
    var
        FromAllObjWithCaption: Record 2000000058;
    begin
        WITH ToAllObjWithCaption DO BEGIN
            FromAllObjWithCaption.SETRANGE("Object Type", "Object Type"::Codeunit);
            FromAllObjWithCaption.SETRANGE("Object Subtype", 'Test');
            IF FromAllObjWithCaption.FIND('-') THEN
                REPEAT
                    ToAllObjWithCaption := FromAllObjWithCaption;
                    INSERT;
                UNTIL FromAllObjWithCaption.NEXT = 0;
        END;

        EXIT(ToAllObjWithCaption.FIND('-'));
    end;

    local procedure GetTestCodeunitsForObjects(var "Object"Record 2000000001; CALTestSuiteName: Code[10])
    var
        TempMissingCUId Record: 2000000026" temporary;
        TempTestCodeunitID Record: 2000000026" temporary;
        CALTestMissingCodeunits: Page130404;
        TestLineNo: Integer;
        TestCodeunitsNumber: Integer;
    begin
        Object.SETFILTER(Type, '<>%1', Object.Type::TableData);
        IF Object.FINDSET THEN BEGIN
            TestCodeunitsNumber := GetTotalTestCodeunitIDs(Object, TempTestCodeunitID);
            OpenWindow(STRSUBSTNO(AddingTestsBasedOnChurnMsg, TestCodeunitsNumber), TestCodeunitsNumber);
            TestLineNo := GetLastTestLineNo(CALTestSuiteName);
            IF TempTestCodeunitID.FINDSET THEN
                REPEAT
                    IF DoesTestCodeunitExist(TempTestCodeunitID.Number) THEN BEGIN
                        IF NOT TestLineExists(CALTestSuiteName, TempTestCodeunitID.Number) THEN BEGIN
                            TestLineNo := TestLineNo + 10000;
                            AddTestLine(CALTestSuiteName, TempTestCodeunitID.Number, TestLineNo);
                            UpdateWindow;
                        END
                    END ELSE BEGIN
                        TempMissingCUId.Number := TempTestCodeunitID.Number;
                        TempMissingCUId.INSERT;
                    END;
                UNTIL TempTestCodeunitID.NEXT = 0;
            Window.CLOSE;
        END ELSE
            MESSAGE(NoModifiedObjectsFoundMsg);

        IF NOT TempMissingCUId.ISEMPTY THEN BEGIN
            COMMIT;
            CALTestMissingCodeunits.Initialize(TempMissingCUId, CALTestSuiteName);
            CALTestMissingCodeunits.RUNMODAL;
        END;
    end;

    local procedure GetTestCodeunitsForModifiedObjects(CALTestSuiteName: Code[10])
    var
        "Object"Record 2000000001;
    begin
        Object.SETRANGE(Modified, TRUE);
        GetTestCodeunitsForObjects(Object, CALTestSuiteName);
    end;

    local procedure GetTestCodeunitsForSelectedObjects(CALTestSuiteName: Code[10])
    var
        "Object"Record 2000000001;
        CALTestObjectsToSelect: Page130407;
    begin
        CALTestObjectsToSelect.LOOKUPMODE := TRUE;
        CALTestObjectsToSelect.SETTABLEVIEW(Object);
        IF CALTestObjectsToSelect.RUNMODAL = ACTION::LookupOK THEN BEGIN
            CALTestObjectsToSelect.SETSELECTIONFILTER(Object);
            GetTestCodeunitsForObjects(Object, CALTestSuiteName);
        END;
    end;

    local procedure GetTotalTestCodeunitIDs(var "Object"Record 2000000001; var TestCodeunitID Record: 2000000026"): Integer
    var
        CALTestCoverageMap: Record 130406;
    begin
        REPEAT
            CALTestCoverageMap.RESET;
            CALTestCoverageMap.SETRANGE("Object ID", Object.ID);
            CALTestCoverageMap.SETRANGE("Object Type", Object.Type);
            IF CALTestCoverageMap.FINDSET THEN
                REPEAT
                    IF NOT TestCodeunitID.GET(CALTestCoverageMap."Test Codeunit ID") THEN BEGIN
                        TestCodeunitID.Number := CALTestCoverageMap."Test Codeunit ID";
                        TestCodeunitID.INSERT;
                    END;
                UNTIL CALTestCoverageMap.NEXT = 0;
        UNTIL Object.NEXT = 0;
        EXIT(TestCodeunitID.COUNT);
    end;

    local procedure GetLastTestLineNo(TestSuiteName: Code[10]) LineNo: Integer
    var
        CALTestLine: Record 130401;
    begin
        CALTestLine.SETRANGE("Test Suite", TestSuiteName);
        IF CALTestLine.FINDLAST THEN
            LineNo := CALTestLine."Line No.";
    end;

    procedure CreateNewSuite(var NewSuiteName: Code[10])
    var
        CALTestSuite: Record 130400;
    begin
        WITH CALTestSuite DO BEGIN
            NewSuiteName := DefaultTxt;
            INIT;
            VALIDATE(Name, NewSuiteName);
            VALIDATE(Description, DefaultSuiteTxt);
            VALIDATE(Export, FALSE);
            INSERT(TRUE);
        END;
    end;

    local procedure RefreshSuite(CALTestSuite Record: 130400; var AllObjWithCaption Record: 2000000058")
    var
        CALTestLine: Record 130401;
        LineNo: Integer;
    begin
        WITH CALTestLine DO BEGIN
            LineNo := LineNo + 10000;

            INIT;
            VALIDATE("Test Suite", CALTestSuite.Name);
            VALIDATE("Line No.", LineNo);
            VALIDATE("Line Type", "Line Type"::Group);
            VALIDATE(Name, DefaultSuiteTxt);
            VALIDATE(Run, TRUE);
            INSERT(TRUE);

            AddTestCodeunits(CALTestSuite, AllObjWithCaption);
        END;
    end;

    procedure AddTestCodeunits(CALTestSuite Record: 130400; var AllObjWithCaption Record: 2000000058")
    var
        TestLineNo: Integer;
    begin
        IF AllObjWithCaption.FIND('-') THEN BEGIN
            TestLineNo := GetLastTestLineNo(CALTestSuite.Name);
            OpenWindow(AddingTestCodeunitsMsg, AllObjWithCaption.COUNT);
            REPEAT
                TestLineNo := TestLineNo + 10000;
                AddTestLine(CALTestSuite.Name, AllObjWithCaption."Object ID", TestLineNo);
                UpdateWindow;
            UNTIL AllObjWithCaption.NEXT = 0;
            Window.CLOSE;
        END;
    end;

    procedure AddMissingTestCodeunits(var TestCodeunitIds Record: 2000000026; TestSuiteName: Code[10])
    var
        "Object"Record 2000000001;
        TestLineNo: Integer;
    begin
        TestLineNo := GetLastTestLineNo(TestSuiteName);
        OpenWindow(STRSUBSTNO(AddingTestsBasedOnChurnMsg, TestCodeunitIds.COUNT), TestCodeunitIds.COUNT);

        REPEAT
            Object.SETRANGE(Type, Object.Type::Codeunit);
            Object.SETRANGE(ID, TestCodeunitIds.Number);
            IF Object.FINDFIRST THEN BEGIN
                TestLineNo := TestLineNo + 10000;
                AddTestLine(TestSuiteName, Object.ID, TestLineNo);
                UpdateWindow;
                TestCodeunitIds.DELETE;
            END;
        UNTIL TestCodeunitIds.NEXT = 0;

        Window.CLOSE;
    end;

    local procedure AddTestLine(TestSuiteName: Code[10]; TestCodeunitId: Integer; LineNo: Integer)
    var
        CALTestLine: Record 130401;
        AllObj: Record 2000000038;
        "Object"Record 2000000001;
        CodeunitIsValid: Boolean;
    begin
        WITH CALTestLine DO BEGIN
            IF TestLineExists(TestSuiteName, TestCodeunitId) THEN
                EXIT;

            INIT;
            VALIDATE("Test Suite", TestSuiteName);
            VALIDATE("Line No.", LineNo);
            VALIDATE("Line Type", "Line Type"::Codeunit);
            VALIDATE("Test Codeunit", TestCodeunitId);
            VALIDATE(Run, TRUE);

            INSERT(TRUE);

            AllObj.SETRANGE("Object Type", AllObj."Object Type"::Codeunit);
            AllObj.SETRANGE("Object ID", TestCodeunitId);
            IF FORMAT(AllObj."App Package ID") <> '' THEN
                CodeunitIsValid := TRUE;

            IF NOT CodeunitIsValid THEN BEGIN
                Object.SETRANGE(Type, Object.Type::Codeunit);
                Object.SETRANGE(ID, TestCodeunitId);
                CodeunitIsValid := Object.FINDFIRST;
            END;

            IF CodeunitIsValid THEN BEGIN
                SETPUBLISHMODE;
                SETRECFILTER;
                CODEUNIT.RUN(CODEUNIT::"CAL Test Runner", CALTestLine);
            END ELSE BEGIN
                VALIDATE(Result, Result::Failure);
                VALIDATE("First Error", ObjectNotCompiledErr);
                MODIFY(TRUE);
            END;
        END;
    end;

    local procedure TestLineExists(TestSuiteName: Code[10]; TestCodeunitId: Integer): Boolean
    var
        CALTestLine: Record 130401;
    begin
        CALTestLine.SETRANGE("Test Suite", TestSuiteName);
        CALTestLine.SETRANGE("Test Codeunit", TestCodeunitId);
        EXIT(NOT CALTestLine.ISEMPTY);
    end;

    [Scope('Personalization')]
    procedure ExtendTestCoverage(TestCodeunitId: Integer)
    var
        CodeCoverage: Record 2000000049;
        CALTestCoverageMap: Record 130406;
    begin
        CodeCoverage.SETRANGE("Line Type", CodeCoverage."Line Type"::Object);
        IF CodeCoverage.FINDSET THEN
            REPEAT
                IF NOT CALTestCoverageMap.GET(TestCodeunitId, CodeCoverage."Object Type", CodeCoverage."Object ID") THEN BEGIN
                    CALTestCoverageMap.INIT;
                    CALTestCoverageMap."Test Codeunit ID" := TestCodeunitId;
                    CALTestCoverageMap."Object Type" := CodeCoverage."Object Type";
                    CALTestCoverageMap."Object ID" := CodeCoverage."Object ID";
                    CALTestCoverageMap.INSERT;
                END;
            UNTIL CodeCoverage.NEXT = 0;
    end;

    local procedure GetLineNoFilter(CALTestLine Record: 130401; Selection: Option ,"Function","Codeunit") LineNoFilter: Text
    var
        NoOfFunctions: Integer;
    begin
        LineNoFilter := '';
        CASE Selection OF
            Selection::"Function":
                BEGIN
                    CALTestLine.TESTFIELD("Line Type", CALTestLine."Line Type"::"Function");
                    LineNoFilter := FORMAT(CALTestLine."Line No.");
                    CALTestLine.RESET;
                    CALTestLine.SETRANGE("Test Suite", CALTestLine."Test Suite");
                    CALTestLine.SETRANGE("Test Codeunit", CALTestLine."Test Codeunit");
                    CALTestLine.SETFILTER("Function", 'OnRun|%1', '');
                    CALTestLine.FINDSET;
                    REPEAT
                        LineNoFilter := LineNoFilter + '|' + FORMAT(CALTestLine."Line No.");
                    UNTIL CALTestLine.NEXT = 0;
                END;
            Selection::Codeunit:
                LineNoFilter :=
                  STRSUBSTNO('%1..%2', CALTestLine.GetMinCodeunitLineNo, CALTestLine.GetMaxCodeunitLineNo(NoOfFunctions));
        END;
    end;

    [Scope('Personalization')]
    procedure RunSelected(var CurrCALTestLine Record: 130401")
    var
        CALTestLine: Record 130401;
        CodeunitIsMarked: Boolean;
        LastCodeunitID: Integer;
        LineNoFilter: Text;
        Selection: Option ,"Function","Codeunit";
        Separator: Text[1];
    begin
        IF CurrCALTestLine.ISEMPTY THEN
            EXIT;
        CALTestLine.COPY(CurrCALTestLine);
        Separator := '';
        LineNoFilter := '';
        CALTestLine.FINDSET;
        REPEAT
            IF CALTestLine."Line Type" = CALTestLine."Line Type"::Codeunit THEN BEGIN
                LineNoFilter := LineNoFilter + Separator + GetLineNoFilter(CALTestLine, Selection::Codeunit);
                LastCodeunitID := CALTestLine."Test Codeunit";
                CodeunitIsMarked := TRUE;
            END ELSE BEGIN
                IF LastCodeunitID <> CALTestLine."Test Codeunit" THEN BEGIN
                    LastCodeunitID := CALTestLine."Test Codeunit";
                    LineNoFilter := LineNoFilter + Separator + GetLineNoFilter(CALTestLine, Selection::"Function");
                    CodeunitIsMarked := FALSE;
                END ELSE
                    IF NOT CodeunitIsMarked THEN
                        LineNoFilter := LineNoFilter + Separator + FORMAT(CALTestLine."Line No.")
            END;
            Separator := '|';
        UNTIL CALTestLine.NEXT = 0;

        CALTestLine.RESET;
        CALTestLine.SETRANGE("Test Suite", CurrCALTestLine."Test Suite");
        CALTestLine.SETFILTER("Line No.", LineNoFilter);
        RunSuite(CALTestLine, TRUE);
    end;

    [Scope('Personalization')]
    procedure RunSuiteYesNo(var CurrCALTestLine Record: 130401")
    var
        CALTestLine: Record 130401;
        Selection: Option ,"Function","Codeunit";
        LineNoFilter: Text;
    begin
        IF CurrCALTestLine.ISEMPTY THEN
            EXIT;
        CALTestLine.COPY(CurrCALTestLine);
        IF CALTestLine."Line Type" = CALTestLine."Line Type"::Codeunit THEN
            Selection := STRMENU(SelectCodeunitsToRunQst, 2)
        ELSE
            Selection := STRMENU(SelectTestsToRunQst, 1);

        IF Selection = 0 THEN
            EXIT;

        LineNoFilter := GetLineNoFilter(CALTestLine, Selection);
        IF LineNoFilter <> '' THEN
            CALTestLine.SETFILTER("Line No.", LineNoFilter);
        RunSuite(CALTestLine, TRUE);
    end;

    [Scope('Personalization')]
    procedure RunSuite(var CALTestLine Record: 130401; IsTestMode: Boolean)
    var
        CALTestLine2Record: Record 130401;
        CALTestRunner: Codeunit 130400;
    begin
        IF IsTestMode THEN BEGIN
            SETTESTMODE;
            CALTestRunner.RUN(CALTestLine);
        END ELSE BEGIN
            SETPUBLISHMODE;
            CALTestLine2.COPY(CALTestLine);
            CALTestLine2.SETRANGE("Line No.", CALTestLine."Line No.");
            CALTestLine2.TESTFIELD("Test Codeunit");
            CALTestLine2.TESTFIELD("Function", '');

            CALTestLine.DeleteChildren;
            CALTestLine2.DeleteChildren;

            CALTestRunner.RUN(CALTestLine2);
        END;
        CLEAR(CALTestRunner);
    end;

    local procedure OpenWindow(DisplayText: Text; NoOfRecords2: Integer)
    begin
        i := 0;
        NoOfRecords := NoOfRecords2;
        WindowUpdateDateTime := CURRENTDATETIME;
        Window.OPEN(DisplayText);
    end;

    local procedure UpdateWindow()
    begin
        i := i + 1;
        IF CURRENTDATETIME - WindowUpdateDateTime >= 1000 THEN BEGIN
            WindowUpdateDateTime := CURRENTDATETIME;
            Window.UPDATE(1, ROUND(i / NoOfRecords * 10000, 1));
        END;
    end;

    [Scope('Personalization')]
    procedure EnableTestToRun()
    var
        CALTestEnabledCodeunit: Record 130403;
        AllObjWithCaption: Record 2000000058;
    begin
        CALTestEnabledCodeunit.DELETEALL;
        AllObjWithCaption.SETRANGE("Object Type", AllObjWithCaption."Object Type"::Codeunit);
        AllObjWithCaption.SETRANGE("Object Subtype", 'Test');
        IF AllObjWithCaption.FINDSET THEN
            REPEAT
                CALTestEnabledCodeunit."No." := 0;
                CALTestEnabledCodeunit."Test Codeunit ID" := AllObjWithCaption."Object ID";
                CALTestEnabledCodeunit.INSERT;
            UNTIL AllObjWithCaption.NEXT = 0;
    end;

    procedure ExportTCM(FileName: Text)
    var
        CALTestCoverageMap: XMLport "130406;
        OutStream: OutStream;
        File: File;
    begin
        IF FileName = '' THEN
            EXIT;

        IF EXISTS(FileName) THEN
            ERASE(FileName);

        IF File.CREATE(FileName) THEN BEGIN
            File.CREATEOUTSTREAM(OutStream);
            CALTestCoverageMap.SETDESTINATION(OutStream);
            CALTestCoverageMap.IMPORTFILE(FALSE);
            CALTestCoverageMap.EXPORT;
            File.CLOSE;
        END;
    end;

    procedure ExportTestResults(FileName: Text; SkipPassed: Boolean; LastTestRun: Boolean)
    var
        CALExportTestResult: XMLport "130403;
        OutStream: OutStream;
        File: File;
    begin
        IF FileName = '' THEN
            EXIT;

        IF EXISTS(FileName) THEN
            ERASE(FileName);

        IF File.CREATE(FileName) THEN BEGIN
            File.CREATEOUTSTREAM(OutStream);
            CALExportTestResult.SetParam(SkipPassed, LastTestRun);
            CALExportTestResult.SETDESTINATION(OutStream);
            CALExportTestResult.IMPORTFILE(FALSE);
            CALExportTestResult.EXPORT;
            File.CLOSE;
        END;
    end;

    procedure ImportTestToRun(FileName: Text; Clean: Boolean)
    var
        CALTestEnabledCodeunit: Record 130403;
        CALImportEnabledCodeunit: XMLport "130402;
        InStream: InStream;
        File: File;
    begin
        IF FileName = '' THEN
            EXIT;

        IF NOT EXISTS(FileName) THEN
            EXIT;

        IF Clean THEN
            CALTestEnabledCodeunit.DELETEALL;

        File.WRITEMODE(FALSE);
        File.OPEN(FileName);
        File.CREATEINSTREAM(InStream);
        CALImportEnabledCodeunit.SETSOURCE(InStream);
        CALImportEnabledCodeunit.IMPORTFILE(TRUE);
        CALImportEnabledCodeunit.IMPORT;
        File.CLOSE;
    end;
}

