codeunit 52506 "Registro de costo"
{

    trigger OnRun()
    begin

        EVALUATE(Hor, '031500');
        IF TIME > Hor THEN
            EXIT;

        RegCostos;
    end;

    var
        PrimeraVez: Boolean;
        PrimeraVez2: Boolean;
        PostValueEntrytoGL: Record 5811;
        PostInventoryCosttoGL: Report 1002;
        Date: Record 2000000007;
        Hor: Time;
        RegistroPDFCostos: Record "Registro PDF Costos";
        TempBlob: Codeunit "Temp Blob";
        PdfOutStream: OutStream;
        PdfInStream: InStream;
        FileName: Text[250];

    procedure RegCostos()
    begin
        PrimeraVez := TRUE;
        PrimeraVez2 := TRUE;

        Date.RESET;
        Date.SETRANGE("Period Type", Date."Period Type"::Date);
        Date.SETRANGE("Period Start", TODAY);

        IF Date.FINDSET THEN
            REPEAT
                IF TIME < Hor THEN BEGIN
                    IF PrimeraVez THEN BEGIN
                        MESSAGE('Inicio valoracion ' + FORMAT(TIME));
                        REPORT.RUN(REPORT::"Adjust Cost - Item Entries", FALSE, TRUE);
                        MESSAGE('Fin valoracion ' + FORMAT(TIME));

                        PrimeraVez := FALSE;
                        COMMIT;
                    END;

                    IF PrimeraVez2 THEN BEGIN
                        RegistroPDFCostos.RESET;
                        RegistroPDFCostos.SETRANGE("Posting Date", Date."Period Start");

                        IF RegistroPDFCostos.ISEMPTY THEN BEGIN
                            PostValueEntrytoGL.RESET;
                            PostValueEntrytoGL.SETRANGE("Posting Date", 0D, NORMALDATE(Date."Period Start"));

                            IF PostValueEntrytoGL.FINDFIRST THEN BEGIN
                                CLEAR(PostInventoryCosttoGL);

                                PostInventoryCosttoGL.InitializeRequest(1, '', TRUE);

                                PostInventoryCosttoGL.SETTABLEVIEW(PostValueEntrytoGL);

                                CLEAR(TempBlob);
                                TempBlob.CREATEOUTSTREAM(PdfOutStream);

                                IF NOT PostInventoryCosttoGL.SaveAs('', ReportFormat::Pdf, PdfOutStream)
                                THEN
                                    ERROR('No se pudo generar el informe de costos correspondiente a la fecha %1.', Date."Period Start");

                                TempBlob.CREATEINSTREAM(PdfInStream);
                                FileName :=
                                    'costos-' + FORMAT(Date."Period Start", 0, '<Day,2><Month,2><Year4>') + '.pdf';

                                RegistroPDFCostos.INIT;
                                RegistroPDFCostos."Posting Date" := Date."Period Start";
                                RegistroPDFCostos."File Name" := FileName;
                                RegistroPDFCostos."Generated At" := CURRENTDATETIME;
                                RegistroPDFCostos."Generated By" := COPYSTR(USERID, 1, MAXSTRLEN(RegistroPDFCostos."Generated By"));

                                RegistroPDFCostos.SetPDF(PdfInStream);
                                RegistroPDFCostos.INSERT(TRUE);

                                CLEAR(PostInventoryCosttoGL);
                                COMMIT;
                            END;
                        END;

                        PrimeraVez2 := FALSE;
                    END;
                END;
            UNTIL Date.NEXT = 0;

        MESSAGE('Fin de tareas nocturnas ');
    end;
}

